export const TIME_SELECT = "TIME_SELECT"
export const CHANGE_PLAY_PAUSE = "CHANGE_PLAY_PAUSE"
export const CHANGE_TIME = "CHANGE_TIME"
export const CHANGES_TIMES_L_S_P = "CHANGES_TIMES_L_S_P"

export const SAFE_CHANGE_TIME = "SAFE_CHANGE_TIME"

//Acount 
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT"

//Auth
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const REGISTER_ERROR  = "REGISTER_ERROR"
export const GET_USER  = "GET_USER"
export const LOGIN_ERROR  = "LOGIN_ERROR"
export const GET_TOKEN_START = "GET_TOKEN_START"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"